### ISSUE TITLE
Faster blockchain import

### ISSUE THREAD

**Issue by Satori-Nakamoto** [cutcoin/cutcoin#1]
Is it possible to allow --verify flag on cutcoin-blockchain-import to do ´--verify 0´ and sync blockchain faster? I get "Failed to parse arguments: unrecognised option '--verify'" error.

**Comment by cutcoin** [comment]
Hi Satori-Nakamoto, you can use './cutcoin-blockchain-import --dangerous-unverified-import' to make the tool ignore the checks. But be carefull and use only trusted .raw file (probably the best way is to generate it by your own). We don't provide official  .raw files yet.

**Comment by Satori-Nakamoto** [comment]
Hi, thanks for your time. Now I see it in ´./cutcoin-blockchain-import --help´ after you mentioned it.
