### ISSUE TITLE
Console re-prints last few characters of new address

### ISSUE THREAD

**Issue by Satori-Nakamoto** [cutcoin/cutcoin#2]
Minor issue- when creating a new account or address, console prints the last few characters of the address into the new line. Pressing enter gives a clean new line to work in.

![accts2](https://user-images.githubusercontent.com/46742164/61995439-4c65d780-b091-11e9-82b1-bb080fdb9ba0.png)

![accounts](https://user-images.githubusercontent.com/46742164/61995416-fc871080-b090-11e9-9172-cb241acb3d94.png)

**Comment by Satori-Nakamoto** [comment]
Also just typing over-wrights those characters.

**Comment by cutcoin** [comment]
Hi Satori-Nakamoto, thank you for the detailed report! What is your terminal and OS versions? I've tried to reproduce the issue, but in my Ubuntu 16.04/Bash it works rather as expected: 
![img](https://user-images.githubusercontent.com/46028258/62057668-bc5a9600-b228-11e9-8228-100b4bb37892.png)

**Comment by Satori-Nakamoto** [comment]
Hi, I just tried on Ubuntu 18.04 and there was no such error. I also just reproduced the error on Linux Mint 18.1 which was the OS I was using when I opened this issue. As for the terminals, I was using the default ones, I guess it's Bash. I'll go ahead and close this issue now, thanks!
