### ISSUE TITLE
Compiling Error on Mac

### ISSUE THREAD

**Issue by wombatlabs** [cutcoin/cutcoin#4]
I ran `brew update && brew bundle --file=contrib/brew/Brewfile` to install the dependencies but when I run `make` I get the following error:

`
-- Found Boost Version: 1.71.0
CMake Error at CMakeLists.txt:875 (message):
  Boost older than 1.62 is too old to link with OpenSSL 1.1 or newer.  Update
  Boost or install OpenSSL 1.0 and set path to it when running cmake: cmake
  -DOPENSSL_ROOT_DIR='/usr/include/openssl-1.0;/usr/lib/openssl-1.0'
`

I am running the latest versions of Boost and OpenSSL.

**Comment by cutcoin** [comment]
Hello! Thank you for your report, we are trying to reproduce the issue and fix / figure out what's going wrong

**Comment by wombatlabs** [comment]
I found the fix:
In `CMakeLists.txt` change line 874 from
`if (Boost_VERSION VERSION_LESS 106200 AND NOT (OPENSSL_VERSION VERSION_LESS 1.1))`

to this

```
  if (Boost_VERSION VERSION_LESS 10 AND Boost_VERSION VERSION_LESS 1.62.0 AND NOT (OPENSSL_VERSION VERSION_LESS 1.1))
    set(BOOST_BEFORE_1_62 true)
  endif()
  if (NOT Boost_VERSION VERSION_LESS 10 AND Boost_VERSION VERSION_LESS 106200 AND NOT (OPENSSL_VERSION VERSION_LESS 1.1))
    set(BOOST_BEFORE_1_62 true)
  endif()
  if (BOOST_BEFORE_1_62)
```
