### ISSUE TITLE
v3 doesn't compile on raspberry pi 3

### ISSUE THREAD

**Issue by Satori-Nakamoto** [cutcoin/cutcoin#5]
This error:

[ 40%] Building CXX object src/rpc/CMakeFiles/obj_daemon_rpc_server.dir/zmq_ser$
/home/pi/cutcoin/src/rpc/zmq_server.cpp: In member function ‘void cryptonote::r$
/home/pi/cutcoin/src/rpc/zmq_server.cpp:41:62: error: no matching function for $
 #define zmq_receiver(socket, message)   (socket->recv(message))
                                                              ^
/home/pi/cutcoin/src/rpc/zmq_server.cpp:74:14: note: in expansion of macro ‘zmq$
       while (zmq_receiver(rep_socket, message))
              ^~~~~~~~~~~~
In file included from /home/pi/cutcoin/src/rpc/zmq_server.h:33,
                 from /home/pi/cutcoin/src/rpc/zmq_server.cpp:30:
/usr/include/zmq.hpp:625:23: note: candidate: ‘size_t zmq::socket_t::recv(void*$
         inline size_t recv (void *buf_, size_t len_, int flags_ = 0)
                       ^~~~
/usr/include/zmq.hpp:625:23: note:   candidate expects 3 arguments, 1 provided
/usr/include/zmq.hpp:635:21: note: candidate: ‘bool zmq::socket_t::recv(zmq::me$
         inline bool recv (message_t *msg_, int flags_ = 0)
                     ^~~~
/usr/include/zmq.hpp:635:21: note:   no known conversion for argument 1 from ‘z$
make[3]: *** [src/rpc/CMakeFiles/obj_daemon_rpc_server.dir/build.make:76: src/r$
make[3]: Leaving directory '/home/pi/cutcoin/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:1963: src/rpc/CMakeFiles/obj_daemon_rpc_serv$
make[2]: Leaving directory '/home/pi/cutcoin/build/Linux/master/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/pi/cutcoin/build/Linux/master/release'
make: *** [Makefile:77: release-all] Error 2

![cuterr](https://user-images.githubusercontent.com/46742164/95113328-f687c780-074a-11eb-9da9-c6ba1b42d994.png)

**Comment by vikpat11** [comment]
I had the same error during compiling on my Pi2

error: no matching function for $
#define zmq_receiver(socket, message) (socket->recv(message))

**Comment by davembg** [comment]
Are you sure you have all the dependencies installed? Looks like it may be missing libzmq3-dev.
Try `sudo apt install libzmq3-dev` maybe?

**Comment by vikpat11** [comment]
> Are you sure you have all the dependencies installed? Looks like it may be missing libzmq3-dev.
> Try `sudo apt install libzmq3-dev` maybe?

It is already installed.

**Comment by Satori-Nakamoto** [comment]
It works by doing

> sudo wget -O /usr/include/zmq.hpp https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp

before building. [Source.](https://github.com/monero-project/monero/issues/2980)
